/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Table } from './Table';
import {
    TableFromJSON,
    TableFromJSONTyped,
    TableToJSON,
} from './Table';

/**
 * 
 * @export
 * @interface Restaurant
 */
export interface Restaurant {
    /**
     * 
     * @type {string}
     * @memberof Restaurant
     */
    name?: string;
    /**
     * 
     * @type {Array<Table>}
     * @memberof Restaurant
     */
    tables?: Array<Table>;
}

/**
 * Check if a given object implements the Restaurant interface.
 */
export function instanceOfRestaurant(value: object): value is Restaurant {
    return true;
}

export function RestaurantFromJSON(json: any): Restaurant {
    return RestaurantFromJSONTyped(json, false);
}

export function RestaurantFromJSONTyped(json: any, ignoreDiscriminator: boolean): Restaurant {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'tables': json['tables'] == null ? undefined : ((json['tables'] as Array<any>).map(TableFromJSON)),
    };
}

export function RestaurantToJSON(value?: Restaurant | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'tables': value['tables'] == null ? undefined : ((value['tables'] as Array<any>).map(TableToJSON)),
    };
}

