/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Table
 */
export interface Table {
    /**
     * 
     * @type {number}
     * @memberof Table
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof Table
     */
    capacity?: number;
    /**
     * 
     * @type {string}
     * @memberof Table
     */
    reservedBy?: string;
    /**
     * 
     * @type {number}
     * @memberof Table
     */
    reservationNumber?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Table
     */
    reserved?: boolean;
}

/**
 * Check if a given object implements the Table interface.
 */
export function instanceOfTable(value: object): value is Table {
    return true;
}

export function TableFromJSON(json: any): Table {
    return TableFromJSONTyped(json, false);
}

export function TableFromJSONTyped(json: any, ignoreDiscriminator: boolean): Table {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'capacity': json['capacity'] == null ? undefined : json['capacity'],
        'reservedBy': json['reservedBy'] == null ? undefined : json['reservedBy'],
        'reservationNumber': json['reservationNumber'] == null ? undefined : json['reservationNumber'],
        'reserved': json['reserved'] == null ? undefined : json['reserved'],
    };
}

export function TableToJSON(value?: Table | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'capacity': value['capacity'],
        'reservedBy': value['reservedBy'],
        'reservationNumber': value['reservationNumber'],
        'reserved': value['reserved'],
    };
}

